// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qv9T3MyWGdu0JkJkGHPP3MbpIgSTysM',
    appId: '1:998290674309:web:10956f0eecbd25bcd04fec',
    messagingSenderId: '998290674309',
    projectId: 'voyage-bfd11',
    authDomain: 'voyage-bfd11.firebaseapp.com',
    storageBucket: 'voyage-bfd11.firebasestorage.app',
    measurementId: 'G-QZ8KG1TC7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoVVr-l86DlhG90GNW20cgLsRNzR1O1cE',
    appId: '1:998290674309:android:6dffeb79860c27d9d04fec',
    messagingSenderId: '998290674309',
    projectId: 'voyage-bfd11',
    storageBucket: 'voyage-bfd11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ESD4t_Mr8lO1JyBYRTk1m24CuG_kxoM',
    appId: '1:998290674309:ios:8b193ec9864b9c82d04fec',
    messagingSenderId: '998290674309',
    projectId: 'voyage-bfd11',
    storageBucket: 'voyage-bfd11.firebasestorage.app',
    iosBundleId: 'com.iit.dme.dmeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ESD4t_Mr8lO1JyBYRTk1m24CuG_kxoM',
    appId: '1:998290674309:ios:8b193ec9864b9c82d04fec',
    messagingSenderId: '998290674309',
    projectId: 'voyage-bfd11',
    storageBucket: 'voyage-bfd11.firebasestorage.app',
    iosBundleId: 'com.iit.dme.dmeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2qv9T3MyWGdu0JkJkGHPP3MbpIgSTysM',
    appId: '1:998290674309:web:d2259cf4d64649ded04fec',
    messagingSenderId: '998290674309',
    projectId: 'voyage-bfd11',
    authDomain: 'voyage-bfd11.firebaseapp.com',
    storageBucket: 'voyage-bfd11.firebasestorage.app',
    measurementId: 'G-VQCEF7SWG6',
  );
}
